[build.environment]
    NEW_KEY = "From Netlify Toml"

[context.production.environment]
    NEW_KEY = "From Netlify Toml"

[context.develop.environment]
    NEW_KEY = "DEV KEY TOML"

[context.develop]
    command = "cp _branchdeploy_headers _headers && npm run build"